# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        exclude: frontend/
        language_version: python3.8
        args: ['--config=backend/pyproject.toml']
  - repo: https://gitlab.com/PyCQA/flake8
    rev: ""
    hooks:
      - id: flake8
        exclude: frontend/
        language_version: python3.8
        args: ['--config=backend/.flake8']
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - svelte@3.30.0
          - prettier@2.2.1
          - prettier-plugin-svelte@1.4.1
        files: \.(js|ts|svelte)$
        exclude: backend/
